### ISSUE TITLE
Count parameter for items that can be crafted in batches

### ISSUE THREAD

**Issue by LordMZTE** [hardliner66/crafting-helper#1]
Let's say I have an item `foo` which 4 of can be crafted with 4 `bars`. if I want to plan out the materials needed for this, I'll get confused because I cannot make 1 `foo` from 1 `bar`. The format currently does not support a count parameter for the number of items made. I would suggest this addition:
```toml
[foo]
tier = 1
name = "Foo"
requirements = { bar = 4 }
count = 4

[bar]
tier = 1
name = "Bar"
```
this would be great, since if I query 1 foo, it would still list 4 bars in the requirements.
currently, the closest I can get is this:
```toml
[foo]
tier = 1
name = "Foo"
requirements = { bar = 1 }

[bar]
tier = 1
name = "Bar"
```
this has the issue that if I query 1 foo, I'd get 1 bar as a requirement. however, if I need 4 bars to make 4 foos, the amount needed will be incorrect.

This issue gets even worse when you get 2 items out and have 1 item as a requirement, because then you will get decimal numbers as well!
